### ISSUE TITLE
GDAX websocket

### ISSUE THREAD

**Issue by chrisdenley** [FGasper/p5-Net-WebSocket#3]
I can't get the GDAX websocket to work. It looks like the handshake works, I send the subscription request, then it ends or something. Am I doing something wrong?
http://www.perlmonks.org/?node_id=1206630
https://docs.gdax.com/?php#websocket-feed

**Comment by FGasper** [comment]
Hey there,

The main reason why this appears not to be working is that you’re not passing a mask to Net::WebSocket::Frame::text->new(). The RFC mandates that clients mask all frames. I really should make this easier …

You’re also not sending the actual serialized form of the frame when you subscribe; you’re sending the frame object, which is going to stringify to something very un-WebSocket-y.

You don’t need two separate IO::Framed objects; just one can do the work. You might as well also defer the IO::Framed creation until after the handshake since that’s when the actual frames come into play.

You should consider adding a `select()` so that you can properly time out and send pings if the peer goes away.

I’m pasting in a patched version of your script:
```
#!/usr/bin/perl
use strict;
use warnings;

use IO::Socket::SSL;
use IO::Framed;
use Net::WebSocket::Frame::text;
use Net::WebSocket::Parser;
use Net::WebSocket::Endpoint::Client;
use Net::WebSocket::Handshake::Client ();
use Net::WebSocket::HTTP_R ();
use HTTP::Response;
use JSON::XS;
use Data::Dumper;

my @prods = qw(BTC-USD LTC-USD ETH-USD);
my $host = 'ws-feed.gdax.com';
my $wssurl = "wss://$host/";
my $port = 443;

my $inet = IO::Socket::SSL->new("$host:$port")
    or die "failed connect or ssl handshake: $!\n$SSL_ERROR";
my $handshake = Net::WebSocket::Handshake::Client->new(
    uri => $wssurl
);
print "REQ HEADERS:\n".$handshake->to_string()."\n";
syswrite $inet, $handshake->to_string() or die $!;
my $buffer = '';
my $cnt = 0;
my $line = <$inet>;
while ($line ne "\r\n") {
    $buffer .= $line;
    $line = <$inet>;
}
print "RESP HEADERS:\n$buffer\n";
my $resp = HTTP::Response->parse($buffer);
Net::WebSocket::HTTP_R::handshake_consume_response( $handshake, $resp );

my $subscribe = {
    type => 'subscribe',
    product_ids => \@prods,
    channels => ['full']
};
my $payload = encode_json($subscribe);
print $payload."\n";
syswrite(
    $inet,
    Net::WebSocket::Frame::text->new(
        payload => $payload,
        mask => Net::WebSocket::Mask::create(),
    )->to_bytes()
);

#See below about IO::Framed
my $iof = IO::Framed->new($inet);

$iof->allow_empty_read();
my $parser = Net::WebSocket::Parser->new( $iof );
my $ept = Net::WebSocket::Endpoint::Client->new(
    parser => $parser,
    out => $iof,
);

$inet->blocking(0);

while(1) {
    while(1) {
        # we are catching up
        print "get next frame\n";
        my $frame = $ept->get_next_message();
        last unless($frame);
        $frame = $frame->get_payload();
        print "\$frame = \"$frame\"\n";
        load_frame($frame);
    }
    # we are caught up
    somethinghard();
    # catch up again
}

sub somethinghard {
    print "something hard\n";
    sleep 1;
}

sub load_frame {
    my ($frame) = @_;
    my $data = decode_json($frame);
    print Dumper($data);
}
```

**Comment by FGasper** [comment]
I’ve pushed up commit 49ea7724cef16483395010975ad863c0bcbf71b1, which contains a new `create_message()` method on Endpoint.pm. That should relieve a bit of the pain that you encountered here—in particular, it handles the mask creation for you so that you don’t need to worry about it.

Closing.
